### PR TITLE
Prototype working

### PR DESCRIPTION
**Pull request by abhisuri97**
look into for loop errors

### CODE REVIEW

**Comment by jarwino** [comment]
There are too many errors. Cannot run locally. Do I need to install any other dependencies? I keep getting syntax errors in the node_modules folder. Are you sure this is working?

**Comment by abhisuri97** [comment]
Download node modules as is. DO NOT npm install

**Comment by jarwino** [comment]
OK it runs locally. Checking for for-loop errors. I had to update node to V4

**Comment by jarwino** [comment]
All fixed.

**Pull request closed without merging**
